# Simple Enhanced Configuration
# Uses key optimizations that work with existing codebase

# Game settings
game_type: gomoku
board_size: 15

# Neural network settings
input_channels: 17
num_res_blocks: 10
num_filters: 64
policy_output_size: 225
use_gpu: true
model_path: "models/model.pt"

# MCTS settings
mcts_num_simulations: 800
mcts_num_threads: 8
mcts_batch_size: 16
mcts_batch_timeout_ms: 5
mcts_virtual_loss: 3.0
mcts_exploration_constant: 1.0
mcts_dirichlet_alpha: 0.3
mcts_dirichlet_epsilon: 0.25

# Self-play settings
num_actors: 8
num_parallel_games: 8
games_per_generation: 10000
save_every_n_games: 100

# Temperature settings
high_temperature: 1.0
low_temperature: 0.1
temperature_threshold: 30

# Enhanced features
transposition_table_size_mb: 1024
enable_thread_affinity: true

# Performance settings
enable_profiling: false
log_level: "INFO"