# 🚀 OPTIMIZED AlphaZero Configuration for 70%+ CPU/GPU Throughput
# Target: Maximum performance with stable memory usage

# Game settings
game_type: gomoku
board_size: 15

# 🔥 HIGH-PERFORMANCE MCTS SETTINGS
mcts_num_simulations: 400          # Keep 400 for good quality
mcts_num_threads: 8                # INCREASED: Use more threads for collection
mcts_batch_size: 32                # Optimal for GPU efficiency
mcts_batch_timeout_ms: 50          # REDUCED: Faster batch formation
mcts_exploration_constant: 1.4
mcts_virtual_loss: 5               # INCREASED: Better thread distribution
mcts_temperature: 1.0

# MCTS Additional settings
mcts_add_dirichlet_noise: true
mcts_dirichlet_alpha: 0.3
mcts_dirichlet_epsilon: 0.25

# Progressive widening - Optimized for speed
mcts_use_progressive_widening: true
mcts_progressive_widening_c: 2.0   # INCREASED: More aggressive expansion
mcts_progressive_widening_k: 0.5   # REDUCED: Slower growth

# Root parallelization - DISABLED (leaf only)
mcts_use_root_parallelization: false
mcts_num_root_workers: 1

# RAVE settings - DISABLED for speed
mcts_use_rave: false
mcts_rave_constant: 0

# Transposition table - Moderate size
mcts_use_transposition_table: true
mcts_transposition_table_size_mb: 64

# Neural network settings
model_path: models/model.pt
num_res_blocks: 10
num_filters: 128

# Self-play settings
self_play_num_games: 10
self_play_num_parallel_games: 1
self_play_max_moves: 0
self_play_temperature_threshold: 30
self_play_high_temperature: 1.0
self_play_low_temperature: 0.1