# Performance test config
game_type: gomoku
board_size: 15
mcts_num_simulations: 200
mcts_num_threads: 8
mcts_batch_size: 64
mcts_batch_timeout_ms: 50
mcts_puct_constant: 1.0
mcts_virtual_loss: 0.5
self_play_num_games: 50
self_play_num_parallel_games: 16
model_path: models/model.pt
model_feature_channels: 256
model_num_blocks: 10
history_length: 7
device: cuda