# Minimal test configuration
game: gomoku
board_size: 15
mcts_simulations: 10
mcts_num_threads: 1
mcts_batch_size: 1
mcts_batch_timeout_ms: 1000
mcts_use_root_parallelization: false
mcts_use_transposition_table: false
model_path: models/model.pt