# Quick test config
game_type: gomoku
board_size: 15

# Gomoku-specific settings  
gomoku_use_renju: true
gomoku_use_omok: false
gomoku_use_pro_long_opening: true

# MCTS settings
mcts_num_simulations: 100  # More simulations to test batching under load
mcts_num_threads: 8        # More threads for increased parallelism
mcts_batch_size: 32        # Even larger batch size
mcts_batch_timeout_ms: 50  # Longer timeout for batch collection

# Self-play settings
self_play_num_games: 1
self_play_num_parallel_games: 1