# Optimized configuration for Ryzen 9 5900X (12c/24t) + RTX 3060 Ti (8GB)

# Game settings
game_type: gomoku
board_size: 15

# Neural network settings
input_channels: 17
num_res_blocks: 10  # Reduced for memory
num_filters: 64     # Reduced from 128 for memory
model_path: "models/model.pt"

# MCTS settings optimized for your hardware
mcts_simulations: 400          # Reduced from 800
mcts_num_threads: 1            # Single thread per engine
mcts_threads_per_engine: 1     # Ensure single thread
mcts_batch_size: 128           # Good for RTX 3060 Ti
mcts_batch_timeout_ms: 5
mcts_c_puct: 1.4
mcts_virtual_loss: 3
mcts_value_init_penalty: 0.3
mcts_root_dirichlet_alpha: 0.3
mcts_root_exploration_fraction: 0.25
mcts_enable_transposition: true
mcts_temperature: 1.0
mcts_temp_threshold: 30

# Self-play settings - optimized for 64GB RAM
num_actors: 100                # Total games
num_parallel_workers: 4        # Only 4 parallel workers (not 12)
games_per_worker: 25           # 25 games per worker = 100 total
num_games: 100
save_interval: 10
verbose: true
output_dir: "data/self_play_games"

# Enhanced features
use_gpu_memory_pool: true
gpu_pool_initial_size_mb: 2048     # 2GB pool for RTX 3060 Ti
gpu_pool_max_size_mb: 4096         # 4GB max (half of VRAM)
gpu_pool_block_sizes: [1048576, 4194304, 16777216]  # 1MB, 4MB, 16MB blocks

# Dynamic batching - optimized for RTX 3060 Ti
use_dynamic_batching: true
dynamic_batch_min_size: 32
dynamic_batch_max_size: 256        # Reasonable max for 8GB VRAM
dynamic_batch_timeout_us: 1000
dynamic_batch_collect_mode: 2      # Adaptive mode

# Advanced transposition table
use_advanced_transposition: true
tt_size_mb: 512                    # 512MB transposition table
tt_num_buckets: 4
tt_enable_compression: true
tt_cache_size: 65536
tt_cleanup_interval: 1000

# Performance tuning
enable_profiling: false
profile_output_dir: "profiles/"
use_cuda_graphs: true
cuda_graph_capture_threads: 2

# Memory management
max_memory_gb: 48                  # Leave 16GB for system
cleanup_threshold_gb: 40
emergency_cleanup_gb: 45

# Training settings (for later)
learning_rate: 0.001
weight_decay: 0.0001
batch_size: 256
replay_buffer_size: 100000
training_steps: 10000
checkpoint_interval: 1000
validation_interval: 100
num_epochs: 1

# Hardware optimization flags
cpu_cores: 12
cpu_threads: 24
gpu_memory_gb: 8
system_memory_gb: 64