# Optimized minimal configuration for fast testing
game_type: gomoku
board_size: 15

# Optimized MCTS settings
mcts:
  num_simulations: 100    # Increased for better play quality
  num_threads: 4         # Use multiple threads for better performance
  exploration_constant: 1.0
  temperature: 1.0
  dirichlet_alpha: 0.25
  dirichlet_epsilon: 0.25
  virtual_loss: 3.0
  
  # Optimized batch settings
  batch_size: 32         # Larger batch for GPU efficiency
  batch_timeout_ms: 20   # Shorter timeout for responsiveness
  
  # Enable optimizations
  use_transposition_table: true
  use_progressive_widening: false
  
  # Memory limits
  transposition_table_size_mb: 64

# Simple neural network
neural_network:
  model_type: resnet
  num_filters: 32
  num_res_blocks: 5
  value_head_hidden_size: 128
  use_batch_norm: false

# Parallel self-play settings
self_play:
  num_games: 10          # Generate 10 games
  max_game_length: 200
  save_games: true
  save_directory: data/self_play_games
  parallel_games: 4      # Run 4 games in parallel

# Debug settings
debug:
  enable_memory_tracking: false  # Disable for performance
  enable_performance_profiling: false
  log_interval_seconds: 10