# 🚀 MEMORY OPTIMIZED AlphaZero Configuration v2.1
# CRITICAL FIX: Using correct config keys to prevent memory explosion

# Game settings
game_type: gomoku
board_size: 15

# 🚀 MEMORY-SAFE GPU UTILIZATION SETTINGS - Prevent OOM while maintaining performance  
mcts_num_simulations: 400          # REDUCED: Prevent memory accumulation
mcts_num_threads: 4                # REDUCED: Lower thread count to reduce memory pressure
mcts_batch_size: 32                # REDUCED: Target 20-24 batches for sustained operation
mcts_max_collection_batch_size: 32  # REDUCED: Conservative to prevent memory explosion
mcts_batch_timeout_ms: 150         # INCREASED: Allow more time for batch formation with fewer threads
mcts_exploration_constant: 1.4
mcts_virtual_loss: 3               # Restored for thread safety
mcts_temperature: 1.0

# MCTS Additional settings
mcts_add_dirichlet_noise: true
mcts_dirichlet_alpha: 0.3
mcts_dirichlet_epsilon: 0.25

# Progressive widening - DISABLED FOR SIMPLICITY
mcts_use_progressive_widening: true
mcts_progressive_widening_c: 1.0
mcts_progressive_widening_k: 10.0

# Root parallelization - ENABLED for maximum throughput
mcts_use_root_parallelization: false
mcts_num_root_workers: 1

# RAVE settings - DISABLED FOR SIMPLICITY
mcts_use_rave: true
mcts_rave_constant: 3000

# Transposition table - REDUCED SIZE
mcts_use_transposition_table: true
mcts_transposition_table_size_mb: 32

# 🔥 Neural network settings - MEMORY-SAFE PERFORMANCE  
model_path: models/model.pt
num_res_blocks: 10                  # REDUCED: Lower memory footprint
num_filters: 128                    # REDUCED: Conservative for memory safety

# Self-play settings - MEMORY-SAFE OPERATION
self_play_num_games: 10             # REDUCED: Prevent memory accumulation over many games
self_play_num_parallel_games: 1    # DISABLED: Sequential games to control memory usage
self_play_max_moves: 0
self_play_temperature_threshold: 30
self_play_high_temperature: 1.0
self_play_low_temperature: 0.1