# Simple DDW test configuration
# Minimal settings for quick testing

# Game settings
game_type: gomoku
board_size: 9
input_channels: 17  # Gomoku enhanced representation

# Network type
network_type: ddw_randwire

# Model path
model_path: models/ddw_test_model.pt

# DDW settings - minimal for testing
ddw_channels: 64
ddw_num_blocks: 5
ddw_num_nodes: 16
ddw_graph_method: watts_strogatz
ddw_ws_p: 0.75
ddw_ws_k: 4
ddw_dynamic_routing: true
ddw_seed: 42

# MCTS settings - minimal
mcts_simulations: 100
mcts_threads_per_engine: 1
mcts_batch_size: 32
mcts_batch_timeout_ms: 10
mcts_c_puct: 1.4
mcts_virtual_loss: 3
mcts_enable_transposition: true
mcts_temperature: 1.0
mcts_temp_threshold: 30

# Self-play settings
num_parallel_workers: 2
num_games: 10
save_interval: 5
output_dir: data/self_play_test

# Quick test mode
max_memory_gb: 8
enable_memory_pool: true