# DDW-RandWire-ResNet Balanced Configuration
# Optimized for Ryzen 9 5900X + RTX 3060 Ti to prevent CPU bottlenecks
# Target: 70-80% GPU utilization with stable performance

# Game settings
game_type: gomoku
board_size: 9
input_channels: 19  # Gomoku enhanced representation with history + attack/defense planes

# Network type selection
network_type: ddw_randwire

# Model path
model_path: models/ddw_randwire_balanced.pt

# DDW-RandWire-ResNet settings - minimal for performance testing
ddw_channels: 32          # Further reduced
ddw_num_blocks: 4         # Minimal blocks
ddw_num_nodes: 6          # Very small graph
ddw_graph_method: watts_strogatz
ddw_ws_p: 0.75
ddw_ws_k: 4
ddw_dynamic_routing: false  # Disabled for performance
ddw_seed: 42

# MCTS settings - balanced for CPU-GPU harmony
mcts_simulations: 400     # Conservative to prevent CPU overload
mcts_threads_per_engine: 8   # Reduced to avoid contention
mcts_batch_size: 32       # Smaller batches for lower latency
mcts_batch_timeout_ms: 10 # Slightly longer timeout
mcts_c_puct: 1.0
mcts_virtual_loss: 3.0
mcts_enable_transposition: false  # DISABLED to avoid overhead
mcts_temperature: 1.0
mcts_temp_threshold: 10
mcts_dirichlet_alpha: 0.25
mcts_dirichlet_epsilon: 0.25
mcts_use_progressive_widening: false  # DISABLED to simplify
mcts_progressive_widening_c: 1.0
mcts_progressive_widening_k: 10.0
mcts_transposition_table_size_mb: 0  # DISABLED

# Parallel settings - conservative for stability
num_parallel_workers: 8   # Increased to better utilize CPU
num_games: 100
save_interval: 10
output_dir: data/self_play_games_ddw_balanced
max_game_length: 200
clear_pools_every_n_games: 10
force_gpu_cleanup_every_n_games: 20

# Memory settings for 64GB RAM
max_memory_gb: 60
cleanup_threshold_gb: 50
emergency_cleanup_gb: 55
enable_memory_pool: false  # DISABLED to reduce overhead
tensor_pool_size: 256      # Reduced
node_pool_initial_size: 2000  # Reduced
node_pool_max_size: 20000     # Reduced
game_state_pool_size: 200     # Reduced
check_interval_ms: 2000       # Less frequent checks
cleanup_interval_ms: 30000    # Much less frequent cleanup

# GPU optimization
cuda_device: 0
gpu_memory_fraction: 0.8  # Conservative GPU memory usage
enable_mixed_precision: false

# Performance expectations:
# - GPU utilization: 60-75% (stable, no CPU bottleneck)
# - Throughput: 200-300 sims/s (consistent)
# - Memory usage: 15-25GB RAM, 3-5GB VRAM
# - No CPU bottlenecks or performance drops