# Optimized ResNet Configuration
# Target: High throughput with stable performance

# Game settings
game_type: gomoku
board_size: 9
input_channels: 19

# Network type selection
network_type: resnet
model_path: models/model.pt

# ResNet settings
num_filters: 128
num_res_blocks: 10

# MCTS settings - optimized for performance
mcts_simulations: 400
mcts_threads_per_engine: 8
mcts_batch_size: 64
mcts_batch_timeout_ms: 5
mcts_c_puct: 1.0
mcts_virtual_loss: 3.0
mcts_enable_transposition: true
mcts_temperature: 1.0
mcts_temp_threshold: 10
mcts_dirichlet_alpha: 0.25
mcts_dirichlet_epsilon: 0.25
mcts_use_progressive_widening: true
mcts_progressive_widening_c: 1.0
mcts_progressive_widening_k: 10.0
mcts_transposition_table_size_mb: 256

# Parallel settings
num_parallel_workers: 8
num_games: 100
save_interval: 10
output_dir: data/self_play_games_resnet
max_game_length: 200
clear_pools_every_n_games: 10
force_gpu_cleanup_every_n_games: 20

# Memory settings for 64GB RAM
max_memory_gb: 60
cleanup_threshold_gb: 50
emergency_cleanup_gb: 55
enable_memory_pool: true
tensor_pool_size: 512
node_pool_initial_size: 10000
node_pool_max_size: 100000
game_state_pool_size: 500
check_interval_ms: 1000
cleanup_interval_ms: 10000

# GPU optimization
cuda_device: 0
gpu_memory_fraction: 0.8
enable_mixed_precision: false

# Expected performance:
# - GPU utilization: 80-95%
# - Throughput: 200-400 sims/s
# - Memory usage: 10-20GB RAM, 2-4GB VRAM
# - Stable performance