# Optimized configuration for memory efficiency and CPU-GPU balance
# Designed for Ryzen 9 5900X (12 cores) + RTX 3060 Ti (8GB VRAM)

# Game settings
game_type: gomoku
board_size: 9

# Neural network settings
input_channels: 19
num_res_blocks: 10
num_filters: 128
model_path: "models/model_gomoku_9x9.pt"

# MCTS settings - optimized for GPU efficiency
mcts_simulations: 400              # Increased for better quality
mcts_threads_per_engine: 7         # Reduced thread contention
mcts_batch_size: 128               # Larger batches for GPU efficiency
mcts_batch_timeout_ms: 50          # Longer timeout for better batching
mcts_c_puct: 1.4
mcts_virtual_loss: 3
mcts_value_init_penalty: 0.3
mcts_root_dirichlet_alpha: 0.3
mcts_root_exploration_fraction: 0.25
mcts_enable_transposition: true
mcts_temperature: 1.0
mcts_temp_threshold: 10

# Parallel settings - optimized for your hardware
num_parallel_workers: 3            # Reduced to prevent GPU contention
num_games: 100
save_interval: 5                   # Save more frequently
verbose: true
output_dir: "data/self_play_games"

# Memory management - aggressive cleanup
max_memory_gb: 16                  # Reduced limit
cleanup_threshold_gb: 12           # Earlier cleanup
emergency_cleanup_gb: 14           # Tighter emergency threshold
gpu_memory_limit_mb: 6000          # Leave 2GB headroom on 8GB GPU
node_pool_compact_interval_ms: 30000  # Regular compaction
clear_gpu_cache_interval: 10       # Clear GPU cache every 10 games