# Optimized configuration for 70%+ CPU/GPU utilization
# Tuned for Ryzen 9 5900X (12 cores/24 threads) + RTX 3060 Ti (8GB VRAM)

# Game settings
game_type: gomoku
board_size: 15

# MCTS settings - optimized for your hardware
mcts_num_simulations: 400
mcts_num_threads: 8  # Reduced from 16 to avoid thread contention
mcts_exploration_constant: 1.4
mcts_dirichlet_alpha: 0.3
mcts_dirichlet_epsilon: 0.25
mcts_batch_size: 32  # Reduced from 64 for better GPU efficiency
mcts_batch_timeout_ms: 50  # Balanced timeout
mcts_virtual_loss: 5  # Balanced for 8 threads
mcts_max_collection_batch_size: 64  # Allow larger collection but smaller GPU batches
mcts_add_dirichlet_noise: true
mcts_temperature: 1.0
mcts_use_transposition_table: true
mcts_transposition_table_size_mb: 256  # Increased for better caching
mcts_use_progressive_widening: true
mcts_progressive_widening_c: 1.0
mcts_progressive_widening_k: 0.5
mcts_use_root_parallelization: false  # Leaf parallelization only
mcts_num_root_workers: 1
mcts_use_rave: true
mcts_rave_constant: 3000.0
mcts_leaf_parallelization: true
mcts_cache_size: 100000
mcts_puct_base: 19652
mcts_puct_init: 1.25

# Self-play settings  
self_play_num_games: 10
self_play_num_parallel_games: 1
self_play_save_interval: 10
self_play_temperature: 1.0
self_play_temperature_threshold: 30
self_play_high_temperature: 1.0
self_play_low_temperature: 0.1
self_play_max_moves: 500
self_play_max_game_length: 500
self_play_noise_epsilon: 0.25
self_play_noise_alpha: 0.3
self_play_output_dir: data/self_play_games
self_play_output_format: json

# Neural network settings - FIXED parameter names
nn_num_filters: 128
nn_num_res_blocks: 10
nn_use_gpu: true
nn_batch_size: 32  # Match MCTS batch size
nn_learning_rate: 0.001
nn_weight_decay: 0.0001
nn_momentum: 0.9
nn_checkpoint_interval: 1000

# Training settings
training_window_size: 500000
training_batch_size: 512
training_num_epochs: 10
training_checkpoint_interval: 100
training_validation_split: 0.1

# Evaluation settings
eval_num_games: 100
eval_win_rate_threshold: 0.55
eval_temperature: 0.1

# Game-specific settings
gomoku_use_renju: true
gomoku_use_omok: false
gomoku_use_pro_long_opening: true
chess_use_chess960: false
go_komi: 7.5
go_chinese_rules: true
go_enforce_superko: true

# System settings
log_level: info
model_path: models/model.pt
training_output_dir: models/checkpoints