# High throughput configuration for 70%+ CPU/GPU utilization
# Optimized for parallel batch processing

# Game settings
game_type: gomoku
board_size: 15

# MCTS optimized settings
mcts_num_simulations: 400
mcts_num_threads: 16  # Increased from 8 for higher CPU utilization
mcts_exploration_constant: 1.4
mcts_dirichlet_alpha: 0.3
mcts_dirichlet_epsilon: 0.25
mcts_batch_size: 64  # Increased from 32 for better GPU utilization
mcts_batch_timeout_ms: 25  # Reduced from 50ms for faster batching
mcts_virtual_loss: 8  # Increased from 5 for better thread collision avoidance
mcts_leaf_parallelization: true
mcts_use_root_parallelization: false
mcts_cache_size: 100000
mcts_progressive_widening_constant: 1.0
mcts_progressive_widening_exponent: 0.5
mcts_evaluation_mode: "neural_network"
mcts_puct_base: 19652
mcts_puct_init: 1.25
mcts_max_collection_batch_size: 128  # Increased for burst processing

# Self-play settings  
self_play_num_games: 10
self_play_save_interval: 10
self_play_temperature: 1.0
self_play_temperature_threshold: 30
self_play_num_parallel_games: 1
self_play_max_game_length: 500
self_play_noise_epsilon: 0.25
self_play_noise_alpha: 0.3

# Neural network settings
nn_num_filters: 128
nn_num_res_blocks: 10
nn_use_gpu: true
nn_batch_size: 64  # Match MCTS batch size
nn_learning_rate: 0.001
nn_weight_decay: 0.0001
nn_momentum: 0.9
nn_checkpoint_interval: 1000

# Training settings
training_window_size: 500000
training_batch_size: 512
training_num_epochs: 10
training_checkpoint_interval: 100
training_validation_split: 0.1

# Evaluation settings
eval_num_games: 100
eval_win_rate_threshold: 0.55
eval_temperature: 0.1

# Optimization features
optimization_burst_mode: true
optimization_adaptive_batching: true
optimization_gpu_streams: 4
optimization_memory_pool_size: 2048
optimization_prefetch_depth: 2

# System settings
log_level: "info"
model_path: "models/model.pt"
self_play_output_dir: "data/self_play_games"
training_output_dir: "models/checkpoints"